Repository kubernetes/kubernetes-docs-ko, pull requests merged in 2018-10, with the labels that each got.

#45 Update translation on tutorials/hello-minikube.md
  content/ko/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#51 Setup page's header and subheader translate into Korean.
  content/ko/docs/setup/independent/_index.md
  content/ko/docs/setup/minikube.md
  content/ko/docs/setup/multiple-zones.md
  content/ko/docs/setup/node-conformance.md
  content/ko/docs/setup/scratch.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#48 Update tutorials for consistency
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/_index.md
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-intro.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
  content/ko/docs/tutorials/kubernetes-basics/index.html
  content/ko/docs/tutorials/kubernetes-basics/scale/_index.md
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#53 up-to-date on content/ko
  content/ko/_common-resources/index.md
  content/ko/docs/setup/_index.md
  content/ko/docs/setup/custom-cloud/kubespray.md
  content/ko/docs/setup/custom-cloud/master.yaml
  content/ko/docs/setup/independent/control-plane-flags.md
  content/ko/docs/setup/independent/create-cluster-kubeadm.md
  content/ko/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/install-kubeadm.md
  content/ko/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/ko/docs/setup/independent/troubleshooting-kubeadm.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/scratch.md
  content/ko/docs/setup/turnkey/gce.md
  content/ko/docs/tutorials/kubernetes-basics/_index.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/ko/examples/minikube/server.js
Labels: approved, cncf-cla: yes, lgtm, size/XL
