Repository kubernetes/kubernetes-docs-ko, pull requests merged in 2018-08, with the labels that each got.

#9 Initial translation of documentation home
  config.toml
  content/ko/docs/home/_index.md
  content/ko/docs/reference/glossary/index.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3 컨트리뷰션 가이드라인 및 저장소 설명 업데이트
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#11 번역할 원본 파일 추가
  content/ko/docs/setup/_index.md
  content/ko/docs/setup/building-from-source.md
  content/ko/docs/setup/cluster-large.md
  content/ko/docs/setup/custom-cloud/_index.md
  content/ko/docs/setup/custom-cloud/coreos.md
  content/ko/docs/setup/custom-cloud/kops.md
  content/ko/docs/setup/custom-cloud/kubespray.md
  content/ko/docs/setup/custom-cloud/master.yaml
  content/ko/docs/setup/custom-cloud/node.yaml
  content/ko/docs/setup/independent/_index.md
  content/ko/docs/setup/independent/control-plane-flags.md
  content/ko/docs/setup/independent/create-cluster-kubeadm.md
  content/ko/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/install-kubeadm.md
  content/ko/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/ko/docs/setup/independent/troubleshooting-kubeadm.md
  content/ko/docs/setup/minikube.md
  content/ko/docs/setup/multiple-zones.md
  content/ko/docs/setup/node-conformance.md
  content/ko/docs/setup/on-premises-vm/_index.md
  content/ko/docs/setup/on-premises-vm/cloudstack.md
  content/ko/docs/setup/on-premises-vm/dcos.md
  content/ko/docs/setup/on-premises-vm/ovirt.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/salt.md
  content/ko/docs/setup/scratch.md
  content/ko/docs/setup/turnkey/_index.md
  content/ko/docs/setup/turnkey/alibaba-cloud.md
  content/ko/docs/setup/turnkey/aws.md
  content/ko/docs/setup/turnkey/azure.md
  content/ko/docs/setup/turnkey/clc.md
  content/ko/docs/setup/turnkey/gce.md
  content/ko/docs/setup/turnkey/stackpoint.md
  content/ko/docs/tutorials/_index.md
  content/ko/docs/tutorials/hello-minikube.md
  content/ko/docs/tutorials/kubernetes-basics/_index.md
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/_index.md
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/_index.md
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
  content/ko/docs/tutorials/kubernetes-basics/explore/_index.md
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-intro.html
  content/ko/docs/tutorials/kubernetes-basics/expose/_index.md
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
  content/ko/docs/tutorials/kubernetes-basics/index.html
  content/ko/docs/tutorials/kubernetes-basics/scale/_index.md
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-intro.html
  content/ko/docs/tutorials/kubernetes-basics/update/_index.md
  content/ko/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
  content/ko/examples/minikube/Dockerfile
  content/ko/examples/minikube/server.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#15 Translate tutorials/kubernetes-basics/create-cluster
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/_index.md
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#16 Translate tutorials/kubernetes-basics/deploy-app in Korean
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/_index.md
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/M
