Repository kubernetes/kubernetes-docs-ko, pull requests merged in 2018-09, with the labels that each got.

#26 Translate tutorials/kubernetes-basics/expose in Korean
  content/ko/docs/tutorials/kubernetes-basics/expose/_index.md
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#24 Translate tutorials/kubernetes-basics/scale in Korean
  content/ko/docs/tutorials/kubernetes-basics/scale/_index.md
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/scale/scale-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#33 [Setup] page's header and sub header translate into Korean.
  content/ko/docs/setup/_index.md
  content/ko/docs/setup/building-from-source.md
  content/ko/docs/setup/cluster-large.md
  content/ko/docs/setup/custom-cloud/_index.md
  content/ko/docs/setup/on-premises-vm/_index.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/turnkey/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#32 Translated the welcome page in Korean
  content/ko/_index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#35 Translate tutorials/kubernetes-basics/update in Korean
  content/ko/docs/tutorials/kubernetes-basics/update/_index.md
  content/ko/docs/tutorials/kubernetes-basics/update/update-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
Labels: cncf-cla: yes, lgtm, size/M

#30 Translate concepts/_index.md in Korean
  content/ko/docs/concepts/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#29 Translate tutorials/kubernetes-basics/index.html in Korean
  content/ko/docs/tutorials/kubernetes-basics/_index.md
  content/ko/docs/tutorials/kubernetes-basics/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#18 Translate /tutorials/hello-minikube.md in Korean
  content/ko/docs/tutorials/hello-minikube.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#36 Translate tutorials/kubernetes-basics/explore in Korean
  content/ko/docs/tutorials/kubernetes-basics/explore/_index.md
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
  content/ko/docs/tutorials/kubernetes-basics/explore/explore-intro.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#42 up-to-date on content/ko
  content/ko/docs/home/_index.md
  content/ko/docs/setup/building-from-source.md
  content/ko/docs/setup/cluster-large.md
  content/ko/docs/setup/custom-cloud/_index.md
  content/ko/docs/setup/custom-cloud/coreos.md
  content/ko/docs/setup/custom-cloud/kops.md
  content/ko/docs/setup/custom-cloud/kubespray.md
  content/ko/docs/setup/custom-cloud/node.yaml
  content/ko/docs/setup/independent/_index.md
  content/ko/docs/setup/independent/create-cluster-kubeadm.md
  content/ko/docs/setup/independent/high-availability.md
  content/ko/docs/setup/independent/install-kubeadm.md
  content/ko/docs/setup/independent/setup-ha-etcd-with-kubeadm.md
  content/ko/docs/setup/independent/troubleshooting-kubeadm.md
  content/ko/docs/setup/minikube.md
  content/ko/docs/setup/multiple-zones.md
  content/ko/docs/setup/on-premises-vm/_index.md
  content/ko/docs/setup/on-premises-vm/ovirt.md
  content/ko/docs/setup/pick-right-solution.md
  content/ko/docs/setup/salt.md
  content/ko/docs/setup/scratch.md
  content/ko/docs/setup/turnkey/_index.md
  content/ko/docs/setup/turnkey/aws.md
  content/ko/docs/setup/turnkey/clc.md
  content/ko/docs/setup/turnkey/gce.md
  content/ko/docs/tutorials/hello-minikube.md
  content/ko/docs/tutorials/kubernetes-basics/_index.md
  content/ko/docs/tutorials/kubernetes-basics/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#41 up-to-date on _index.html
  content/ko/_common-resources/index.md
  content/ko/_index.html
  content/ko/case-studies/_index.html
  content/ko/docs/concepts/overview/what-is-kubernetes.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 Translate tutorials/_index.md in Korean
  content/ko/docs/tutorials/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/M
